CREATE TABLE IF NOT EXISTS [Loan] (
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT NOT NULL,
    [ModifiedAt] TEXT NOT NULL,
    [Amount] INTEGER NOT NULL,
    FOREIGN KEY(BankUserId) REFERENCES BankUser(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS [BankUser](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [UserId] INTEGER NOT NULL,
    [CreatedAt] TEXT NOT NULL,
    [ModifiedAt] TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS [Deposit](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL,
    [CreatedAt] TEXT NOT NULL,
    [Amount] INTEGER NOT NULL,
    FOREIGN KEY(BankUserId) REFERENCES BankUser(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS [Account](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BankUserId] INTEGER NOT NULL UNIQUE,
    [AccountNo] TEXT  NOT NULL UNIQUE,
    [IsStudent] TEXT NOT NULL,
    [CreatedAt] TEXT NOT NULL,
    [ModifiedAt] TEXT NOT NULL,
    [Amount] INTEGER NOT NULL,
    FOREIGN KEY(BankUserId) REFERENCES BankUser(Id) ON DELETE CASCADE
);