DROP TABLE [BorgerUser]

CREATE TABLE [BorgerUser](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [UserId] TEXT NOT NULL UNIQUE,
    [CreatedAt] TEXT NOT NULL
);

CREATE TABLE [Address](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [Address] TEXT NOT NULL,
    [IsValid] DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ([BorgerUserId]) REFERENCES [BorgerUser](Id)
);