CREATE TABLE [BorgerUser](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [UserId] TEXT NOT NULL UNIQUE,
    [CreatedAt] TEXT NOT NULL
);


CREATE TABLE [Address](
    [Id] INTEGER PRIMARY KEY AUTOINCREMENT,
    [BorgerUserId] INTEGER NOT NULL,
    [Address] TEXT NOT NULL,
    [CreatedAt] TEXT NOT NULL,
    [IsValid] TEXT NOT NULL,
    FOREIGN KEY (BorgerUserId) REFERENCES BorgerUser(Id)
);

DELETE FROM Address;